### ISSUE TITLE
update the parameter name

### ISSUE THREAD

**Issue by Andy320** [rib/jsonwebtokens#1]
Please use the more suitable name in the veryfier.rs .

In the line 261, 
issuer -> aud

**Comment by rib** [comment]
Ah, well spotted, thanks! just pushed a fix to master.

I'll push a release to crates.io soon too - probably after renaming the various `.claim_equals`, `.claim_matches` '.claim_xyz` VerifierBuilder apis to instead be `.string_equals`, `.string_xyz` to be more explicit that they are for string claims, and make it possible to configure verification of numeric claims too.
