### ISSUE TITLE
Error on README examples

### ISSUE THREAD

**Issue by ddibiase** [rib/jsonwebtokens#2]
All string_matches() statements on the README are incorrectly using a string as the matching parameter. Should be using a regex type:

```rust
.string_matches("my_claim", Regex::new("[fo]+").unwrap())
```

**Comment by rib** [comment]
Ah, thanks for the pointer and sorry for the delay responding to this.

**Comment by rib** [comment]
Just pushed an update (853411e0150bfb029f79cba1d13fbec9d175a98a) to the README.md for this - thanks again.
